### ISSUE TITLE
Formatting codes come through for team prefixes and /say command

### ISSUE THREAD

**Issue by R6219** [hypherionmc/sdlink#53] opened 2023-04-23 16:32 UTC
If a vanilla team has been assigned a prefix with a color (using /team modify <teamname> prefix <prefix>), the formatting codes (section sign § characters and their following assignment) get transmitted to Discord. The player below belongs to the [OP] team:

![image](https://user-images.githubusercontent.com/85911470/233851709-0ce82526-e1d0-449d-9aab-52f02de1cc22.png)

And here's how their name comes through on the Discord channel:

![image](https://user-images.githubusercontent.com/85911470/233851880-a13cf9fc-f080-49b7-8158-aa8b3d6e3852.png)
![image](https://user-images.githubusercontent.com/85911470/233851641-926d68cd-96f3-4dc7-abe2-2ed9c6bc2e7e.png)

Additionally, these codes come through when using the /say command. 

Using fabric/quilt release 1.19.3-2.2.1.

**Comment by hypherionmc** [comment] 2023-04-23 17:08
I'm guessing the /team command is from a mod.

If that is the case, we do not officially support any mods that add prefixes or colors to usernames, because they end up using weird formatting code like that. 

It's something we're looking at improving with the v3 release, since we are rewriting the entire mod

**Comment by R6219** [comment] 2023-04-23 17:40
The /team command is a vanilla feature commonly used on servers, and often in datapacks: https://minecraft.fandom.com/wiki/Commands/team

**Comment by hypherionmc** [comment] 2023-04-23 17:48
Interesting. Didn't even know about that command... TIL

Will take a look into it. Thanks for reporting

**Comment by hypherionmc** [comment] 2023-05-21 13:24
So far, this issue has been revolved with the V3 development. Did some basic testing, and the codes appear to be stripped now. If you want, you can send me the formatting for the issue you reported, so I can confirm that it properly strips the codes

**Comment by R6219** [comment] 2023-05-22 03:57
Glad to hear it! Thanks for taking this on. The particular formatting in the reported issue can be replicated in-game using these commands:

```
/team add op.team

/team modify op.team prefix "\u00A78[\u00A7d\u00A7k_\u00A7r\u00A76OP\u00A7d\u00A7k_\u00A7r\u00A78]"

/team join op.team @s
```

This creates a team "op.team", changes its prefix to the formatted json text in the quotes, and joins the player who sends the command to the team. Messages typed in chat by the team member should then display the prefix next to the name.

**Comment by R6219** [comment] 2023-05-22 04:04
Would you mind testing for formatting codes in other places, such as a with ```/say``` message? For example, would ```say §dhi``` (sent from the server console) also strip the formatting code in the Discord message?

**Comment by hypherionmc** [comment] 2023-05-22 06:29
I will test with both. Once V3 is stable enough to be used, would you mind being a beta tester? I want the V3 release to go out without any bugs (or atleast little to no bugs)

**Comment by R6219** [comment] 2023-05-22 12:00
I'd be happy to! How do I do that?

**Comment by hypherionmc** [comment] 2023-05-22 14:51
We provide the builds on our Jenkins server, but there aren't any available yet. As soon as there is a build available, I will give you a shout. If you are in our Discord Server, you should receive the ping as well

**Comment by hypherionmc** [comment] 2023-06-11 15:14
Since I finally have time to work on V3 again, I can now confirm this issue is fixed in V3.

Top one is the say command, bottom one is normal chat, with team assigned

![Image](https://github.com/hypherionmc/sdlink/assets/63595580/022ddcf8-e17a-41c4-8e21-534791f11151)

**Comment by hypherionmc** [comment] 2023-12-03 06:22
Implemented in V3 beta

**Closed as completed by hypherionmc** 2023-12-03 06:22 UTC
Labels: v3 rewrite
